spring:
  application:
    name: orbitfire-hotspots-ms

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

orbitfire:
  aws:
    region: us-east-1
    profile: ${AWS_PROFILE:}
    s3:
      bucket-name: ${BUCKET_NAME}
      daily-prefix: ${DAILY_PREFIX}
      monthly-prefix: ${MONTHLY_PREFIX}
      metadata: ${METADATA}
  cache:
    metadata-ttl-minutes: 10
    daily-ttl-minutes: 30
    monthly-ttl-minutes: 120
  security:
    allowed-origin: ${FRONTEND_URL}
